name: Build and deploy to GitHub Pages

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout/@v4

      - name: Install
        run: npm ci

      - name: Run format test
        run: npm run test-format

      - name: Run unit tests
        run: npm run test-jest

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
